# Travis CI does not support multiple languages, but Nodejs is also installed on PHP environments (but PHP is not
# installed on Nodejs environments, therefore use a PHP machine and to setup and execution manually.
language: php
php:
    5.5
node_js:
    - 0.10
before_install:
  - npm install -g grunt-cli
  - npm install
script:
  - npm test
