#!/usr/bin/env php
<?php

define('TMP_DIR', realpath(__DIR__.'/../..').'/tmp');

echo TMP_DIR."\n";

$args = implode(' ', array_slice($_SERVER['argv'], 1))."\n";

if (false === file_exists(TMP_DIR)) {
    mkdir(TMP_DIR);
}
$filename = trim(preg_replace('/(-|\s|=|:)+/', '_', trim($args)), '_');
file_put_contents(TMP_DIR.'/'.$filename, $args);

echo $args;
